FROM eclipse-temurin:21-jdk

WORKDIR /app

COPY . .

RUN apt-get update && apt-get install -y maven

RUN mvn clean package -DskipTests

CMD ["sh", "-c", "java -Dserver.port=${PORT:-10000} -jar target/*.jar"]