spring.application.name=roasting-monitor-api
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/roasting_monitor
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.serialization.write-dates-as-timestamps=false
